packageName: "algokit_msgpack_ffi"
packageVersion: "0.1.0"
packageUrl: "https://github.com/algorandfoundation/algokit-core"
packageDescription: "FFI bindings for Algorand msgpack operations"
packageAuthor: "Algorand Foundation"
packageLicense: "MIT"
packageRepository: "https://github.com/algorandfoundation/algokit-core"
packageHomepage: "https://github.com/algorandfoundation/algokit-core"
packageDocumentation: "https://github.com/algorandfoundation/algokit-core"

# Generate models only
additionalProperties:
  generateModels: true
  generateApis: false
  avoidBoxedModels: true

typeMappings:
  object: String

# Custom files to include - only the mod.rs for models
files:
  model_mod.mustache:
    templateType: SupportingFiles
    folder: "src/models"
    destinationFilename: "mod.rs"

