[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[project]
name = "algokit_msgpack"
version = "1.0.0"
requires-python = ">=3.8,<4.0"
dependencies = ["cffi>=1.17.1"]

[tool.maturin]
manifest-path = "../../../crates/algokit_msgpack_ffi/Cargo.toml"

module-name = "_algokit_msgpack"

include = ["algokit_msgpack/py.typed", "algokit_msgpack/__init__.py"]


[tool.poetry.group.dev.dependencies]
maturin = [
  { version = ">=1.8.2", markers = "platform_system != 'Linux'" },
  { version = ">=1.8.2", extras = [
    "patchelf",
  ], markers = "platform_system == 'Linux'" },
]
pynacl = ">=1.5.0,<2.0.0"
pytest = ">=7.4.4"
