/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::Account;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct AccountsResponse {
    #[serde(rename = "accounts")]
    pub accounts: Vec<Account>,
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: u64,
    /// Used for pagination, when making another request provide this token with the next parameter.
    #[serde(rename = "next-token", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
}

impl AccountsResponse {
    /// Constructor for AccountsResponse
    pub fn new(accounts: Vec<Account>, current_round: u64) -> AccountsResponse {
        AccountsResponse {
            accounts,
            current_round,
            next_token: None,
        }
    }
}
