/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An catchpoint abort response.
 * @export
 * @interface AbortCatchup200Response
 */
export interface AbortCatchup200Response {
    /**
     * Catchup abort response string
     * @type {string}
     * @memberof AbortCatchup200Response
     */
    catchupMessage: string;
}

/**
 * Check if a given object implements the AbortCatchup200Response interface.
 */
export function instanceOfAbortCatchup200Response(value: object): value is AbortCatchup200Response {
    if (!('catchupMessage' in value) || value['catchupMessage'] === undefined) return false;
    return true;
}

export function AbortCatchup200ResponseFromJSON(json: any): AbortCatchup200Response {
    return AbortCatchup200ResponseFromJSONTyped(json, false);
}

export function AbortCatchup200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbortCatchup200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'catchupMessage': json['catchup-message'],
    };
}

export function AbortCatchup200ResponseToJSON(json: any): AbortCatchup200Response {
    return AbortCatchup200ResponseToJSONTyped(json, false);
}

export function AbortCatchup200ResponseToJSONTyped(value?: AbortCatchup200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'catchup-message': value['catchupMessage'],
    };
}

