/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetParams } from './AssetParams';
import {
    AssetParamsFromJSON,
    AssetParamsFromJSONTyped,
    AssetParamsToJSON,
    AssetParamsToJSONTyped,
} from './AssetParams';
import type { AssetHolding } from './AssetHolding';
import {
    AssetHoldingFromJSON,
    AssetHoldingFromJSONTyped,
    AssetHoldingToJSON,
    AssetHoldingToJSONTyped,
} from './AssetHolding';

/**
 * 
 * @export
 * @interface AccountAssetInformation200Response
 */
export interface AccountAssetInformation200Response {
    /**
     * The round for which this information is relevant.
     * @type {number}
     * @memberof AccountAssetInformation200Response
     */
    round: number;
    /**
     * 
     * @type {AssetHolding}
     * @memberof AccountAssetInformation200Response
     */
    assetHolding?: AssetHolding;
    /**
     * 
     * @type {AssetParams}
     * @memberof AccountAssetInformation200Response
     */
    createdAsset?: AssetParams;
}

/**
 * Check if a given object implements the AccountAssetInformation200Response interface.
 */
export function instanceOfAccountAssetInformation200Response(value: object): value is AccountAssetInformation200Response {
    if (!('round' in value) || value['round'] === undefined) return false;
    return true;
}

export function AccountAssetInformation200ResponseFromJSON(json: any): AccountAssetInformation200Response {
    return AccountAssetInformation200ResponseFromJSONTyped(json, false);
}

export function AccountAssetInformation200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountAssetInformation200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'round': json['round'],
        'assetHolding': json['asset-holding'] == null ? undefined : AssetHoldingFromJSON(json['asset-holding']),
        'createdAsset': json['created-asset'] == null ? undefined : AssetParamsFromJSON(json['created-asset']),
    };
}

export function AccountAssetInformation200ResponseToJSON(json: any): AccountAssetInformation200Response {
    return AccountAssetInformation200ResponseToJSONTyped(json, false);
}

export function AccountAssetInformation200ResponseToJSONTyped(value?: AccountAssetInformation200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'round': value['round'],
        'asset-holding': AssetHoldingToJSON(value['assetHolding']),
        'created-asset': AssetParamsToJSON(value['createdAsset']),
    };
}

