/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddParticipationKey200Response
 */
export interface AddParticipationKey200Response {
    /**
     * encoding of the participation ID.
     * @type {string}
     * @memberof AddParticipationKey200Response
     */
    partId: string;
}

/**
 * Check if a given object implements the AddParticipationKey200Response interface.
 */
export function instanceOfAddParticipationKey200Response(value: object): value is AddParticipationKey200Response {
    if (!('partId' in value) || value['partId'] === undefined) return false;
    return true;
}

export function AddParticipationKey200ResponseFromJSON(json: any): AddParticipationKey200Response {
    return AddParticipationKey200ResponseFromJSONTyped(json, false);
}

export function AddParticipationKey200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddParticipationKey200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'partId': json['partId'],
    };
}

export function AddParticipationKey200ResponseToJSON(json: any): AddParticipationKey200Response {
    return AddParticipationKey200ResponseToJSONTyped(json, false);
}

export function AddParticipationKey200ResponseToJSONTyped(value?: AddParticipationKey200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'partId': value['partId'],
    };
}

