/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApplicationParams } from './ApplicationParams';
import {
    ApplicationParamsFromJSON,
    ApplicationParamsFromJSONTyped,
    ApplicationParamsToJSON,
    ApplicationParamsToJSONTyped,
} from './ApplicationParams';

/**
 * Application index and its parameters
 * @export
 * @interface Application
 */
export interface Application {
    /**
     * \[appidx\] application index.
     * @type {number}
     * @memberof Application
     */
    id: number;
    /**
     * 
     * @type {ApplicationParams}
     * @memberof Application
     */
    params: ApplicationParams;
}

/**
 * Check if a given object implements the Application interface.
 */
export function instanceOfApplication(value: object): value is Application {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('params' in value) || value['params'] === undefined) return false;
    return true;
}

export function ApplicationFromJSON(json: any): Application {
    return ApplicationFromJSONTyped(json, false);
}

export function ApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Application {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'params': ApplicationParamsFromJSON(json['params']),
    };
}

export function ApplicationToJSON(json: any): Application {
    return ApplicationToJSONTyped(json, false);
}

export function ApplicationToJSONTyped(value?: Application | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'params': ApplicationParamsToJSON(value['params']),
    };
}

