/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Specifies maximums on the number of each type that may be stored.
 * @export
 * @interface ApplicationStateSchema
 */
export interface ApplicationStateSchema {
    /**
     * \[nui\] num of uints.
     * @type {number}
     * @memberof ApplicationStateSchema
     */
    numUint: number;
    /**
     * \[nbs\] num of byte slices.
     * @type {number}
     * @memberof ApplicationStateSchema
     */
    numByteSlice: number;
}

/**
 * Check if a given object implements the ApplicationStateSchema interface.
 */
export function instanceOfApplicationStateSchema(value: object): value is ApplicationStateSchema {
    if (!('numUint' in value) || value['numUint'] === undefined) return false;
    if (!('numByteSlice' in value) || value['numByteSlice'] === undefined) return false;
    return true;
}

export function ApplicationStateSchemaFromJSON(json: any): ApplicationStateSchema {
    return ApplicationStateSchemaFromJSONTyped(json, false);
}

export function ApplicationStateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationStateSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'numUint': json['num-uint'],
        'numByteSlice': json['num-byte-slice'],
    };
}

export function ApplicationStateSchemaToJSON(json: any): ApplicationStateSchema {
    return ApplicationStateSchemaToJSONTyped(json, false);
}

export function ApplicationStateSchemaToJSONTyped(value?: ApplicationStateSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'num-uint': value['numUint'],
        'num-byte-slice': value['numByteSlice'],
    };
}

