/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AvmKeyValue } from './AvmKeyValue';
import {
    AvmKeyValueFromJSON,
    AvmKeyValueFromJSONTyped,
    AvmKeyValueToJSON,
    AvmKeyValueToJSONTyped,
} from './AvmKeyValue';

/**
 * An application's global/local/box state.
 * @export
 * @interface ApplicationKVStorage
 */
export interface ApplicationKVStorage {
    /**
     * Key-Value pairs representing application states.
     * @type {Array<AvmKeyValue>}
     * @memberof ApplicationKVStorage
     */
    kvs: Array<AvmKeyValue>;
    /**
     * The address of the account associated with the local state.
     * @type {string}
     * @memberof ApplicationKVStorage
     */
    account?: string;
}

/**
 * Check if a given object implements the ApplicationKVStorage interface.
 */
export function instanceOfApplicationKVStorage(value: object): value is ApplicationKVStorage {
    if (!('kvs' in value) || value['kvs'] === undefined) return false;
    return true;
}

export function ApplicationKVStorageFromJSON(json: any): ApplicationKVStorage {
    return ApplicationKVStorageFromJSONTyped(json, false);
}

export function ApplicationKVStorageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationKVStorage {
    if (json == null) {
        return json;
    }
    return {
        
        'kvs': ((json['kvs'] as Array<any>).map(AvmKeyValueFromJSON)),
        'account': json['account'] == null ? undefined : json['account'],
    };
}

export function ApplicationKVStorageToJSON(json: any): ApplicationKVStorage {
    return ApplicationKVStorageToJSONTyped(json, false);
}

export function ApplicationKVStorageToJSONTyped(value?: ApplicationKVStorage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kvs': ((value['kvs'] as Array<any>).map(AvmKeyValueToJSON)),
        'account': value['account'],
    };
}

