/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * AssetParams specifies the parameters for an asset.
 * 
 * \[apar\] when part of an AssetConfig transaction.
 * 
 * Definition:
 * data/transactions/asset.go : AssetParams
 * @export
 * @interface AssetParams
 */
export interface AssetParams {
    /**
     * \[c\] Address of account used to clawback holdings of this asset.  If empty, clawback is not permitted.
     * @type {string}
     * @memberof AssetParams
     */
    clawback?: string;
    /**
     * The address that created this asset. This is the address where the parameters for this asset can be found, and also the address where unwanted asset units can be sent in the worst case.
     * @type {string}
     * @memberof AssetParams
     */
    creator: string;
    /**
     * \[dc\] The number of digits to use after the decimal point when displaying this asset. If 0, the asset is not divisible. If 1, the base unit of the asset is in tenths. If 2, the base unit of the asset is in hundredths, and so on. This value must be between 0 and 19 (inclusive).
     * @type {number}
     * @memberof AssetParams
     */
    decimals: number;
    /**
     * \[df\] Whether holdings of this asset are frozen by default.
     * @type {boolean}
     * @memberof AssetParams
     */
    defaultFrozen?: boolean;
    /**
     * \[f\] Address of account used to freeze holdings of this asset.  If empty, freezing is not permitted.
     * @type {string}
     * @memberof AssetParams
     */
    freeze?: string;
    /**
     * \[m\] Address of account used to manage the keys of this asset and to destroy it.
     * @type {string}
     * @memberof AssetParams
     */
    manager?: string;
    /**
     * \[am\] A commitment to some unspecified asset metadata. The format of this metadata is up to the application.
     * @type {string}
     * @memberof AssetParams
     */
    metadataHash?: string;
    /**
     * \[an\] Name of this asset, as supplied by the creator. Included only when the asset name is composed of printable utf-8 characters.
     * @type {string}
     * @memberof AssetParams
     */
    name?: string;
    /**
     * Base64 encoded name of this asset, as supplied by the creator.
     * @type {string}
     * @memberof AssetParams
     */
    nameB64?: string;
    /**
     * \[r\] Address of account holding reserve (non-minted) units of this asset.
     * @type {string}
     * @memberof AssetParams
     */
    reserve?: string;
    /**
     * \[t\] The total number of units of this asset.
     * @type {number}
     * @memberof AssetParams
     */
    total: number;
    /**
     * \[un\] Name of a unit of this asset, as supplied by the creator. Included only when the name of a unit of this asset is composed of printable utf-8 characters.
     * @type {string}
     * @memberof AssetParams
     */
    unitName?: string;
    /**
     * Base64 encoded name of a unit of this asset, as supplied by the creator.
     * @type {string}
     * @memberof AssetParams
     */
    unitNameB64?: string;
    /**
     * \[au\] URL where more information about the asset can be retrieved. Included only when the URL is composed of printable utf-8 characters.
     * @type {string}
     * @memberof AssetParams
     */
    url?: string;
    /**
     * Base64 encoded URL where more information about the asset can be retrieved.
     * @type {string}
     * @memberof AssetParams
     */
    urlB64?: string;
}

/**
 * Check if a given object implements the AssetParams interface.
 */
export function instanceOfAssetParams(value: object): value is AssetParams {
    if (!('creator' in value) || value['creator'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function AssetParamsFromJSON(json: any): AssetParams {
    return AssetParamsFromJSONTyped(json, false);
}

export function AssetParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetParams {
    if (json == null) {
        return json;
    }
    return {
        
        'clawback': json['clawback'] == null ? undefined : json['clawback'],
        'creator': json['creator'],
        'decimals': json['decimals'],
        'defaultFrozen': json['default-frozen'] == null ? undefined : json['default-frozen'],
        'freeze': json['freeze'] == null ? undefined : json['freeze'],
        'manager': json['manager'] == null ? undefined : json['manager'],
        'metadataHash': json['metadata-hash'] == null ? undefined : json['metadata-hash'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameB64': json['name-b64'] == null ? undefined : json['name-b64'],
        'reserve': json['reserve'] == null ? undefined : json['reserve'],
        'total': json['total'],
        'unitName': json['unit-name'] == null ? undefined : json['unit-name'],
        'unitNameB64': json['unit-name-b64'] == null ? undefined : json['unit-name-b64'],
        'url': json['url'] == null ? undefined : json['url'],
        'urlB64': json['url-b64'] == null ? undefined : json['url-b64'],
    };
}

export function AssetParamsToJSON(json: any): AssetParams {
    return AssetParamsToJSONTyped(json, false);
}

export function AssetParamsToJSONTyped(value?: AssetParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clawback': value['clawback'],
        'creator': value['creator'],
        'decimals': value['decimals'],
        'default-frozen': value['defaultFrozen'],
        'freeze': value['freeze'],
        'manager': value['manager'],
        'metadata-hash': value['metadataHash'],
        'name': value['name'],
        'name-b64': value['nameB64'],
        'reserve': value['reserve'],
        'total': value['total'],
        'unit-name': value['unitName'],
        'unit-name-b64': value['unitNameB64'],
        'url': value['url'],
        'url-b64': value['urlB64'],
    };
}

