/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes an asset held by an account.
 * 
 * Definition:
 * data/basics/userBalance.go : AssetHolding
 * @export
 * @interface AssetHolding
 */
export interface AssetHolding {
    /**
     * \[a\] number of units held.
     * @type {number}
     * @memberof AssetHolding
     */
    amount: number;
    /**
     * Asset ID of the holding.
     * @type {number}
     * @memberof AssetHolding
     */
    assetId: number;
    /**
     * \[f\] whether or not the holding is frozen.
     * @type {boolean}
     * @memberof AssetHolding
     */
    isFrozen: boolean;
}

/**
 * Check if a given object implements the AssetHolding interface.
 */
export function instanceOfAssetHolding(value: object): value is AssetHolding {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('assetId' in value) || value['assetId'] === undefined) return false;
    if (!('isFrozen' in value) || value['isFrozen'] === undefined) return false;
    return true;
}

export function AssetHoldingFromJSON(json: any): AssetHolding {
    return AssetHoldingFromJSONTyped(json, false);
}

export function AssetHoldingFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetHolding {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'assetId': json['asset-id'],
        'isFrozen': json['is-frozen'],
    };
}

export function AssetHoldingToJSON(json: any): AssetHolding {
    return AssetHoldingToJSONTyped(json, false);
}

export function AssetHoldingToJSONTyped(value?: AssetHolding | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'asset-id': value['assetId'],
        'is-frozen': value['isFrozen'],
    };
}

