/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetParams } from './AssetParams';
import {
    AssetParamsFromJSON,
    AssetParamsFromJSONTyped,
    AssetParamsToJSON,
    AssetParamsToJSONTyped,
} from './AssetParams';

/**
 * Specifies both the unique identifier and the parameters for an asset
 * @export
 * @interface Asset
 */
export interface Asset {
    /**
     * unique asset identifier
     * @type {number}
     * @memberof Asset
     */
    index: number;
    /**
     * 
     * @type {AssetParams}
     * @memberof Asset
     */
    params: AssetParams;
}

/**
 * Check if a given object implements the Asset interface.
 */
export function instanceOfAsset(value: object): value is Asset {
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('params' in value) || value['params'] === undefined) return false;
    return true;
}

export function AssetFromJSON(json: any): Asset {
    return AssetFromJSONTyped(json, false);
}

export function AssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Asset {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'params': AssetParamsFromJSON(json['params']),
    };
}

export function AssetToJSON(json: any): Asset {
    return AssetToJSONTyped(json, false);
}

export function AssetToJSONTyped(value?: Asset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'params': AssetParamsToJSON(value['params']),
    };
}

