/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AvmValue } from './AvmValue';
import {
    AvmValueFromJSON,
    AvmValueFromJSONTyped,
    AvmValueToJSON,
    AvmValueToJSONTyped,
} from './AvmValue';

/**
 * Represents an AVM key-value pair in an application store.
 * @export
 * @interface AvmKeyValue
 */
export interface AvmKeyValue {
    /**
     * 
     * @type {string}
     * @memberof AvmKeyValue
     */
    key: string;
    /**
     * 
     * @type {AvmValue}
     * @memberof AvmKeyValue
     */
    value: AvmValue;
}

/**
 * Check if a given object implements the AvmKeyValue interface.
 */
export function instanceOfAvmKeyValue(value: object): value is AvmKeyValue {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function AvmKeyValueFromJSON(json: any): AvmKeyValue {
    return AvmKeyValueFromJSONTyped(json, false);
}

export function AvmKeyValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvmKeyValue {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': AvmValueFromJSON(json['value']),
    };
}

export function AvmKeyValueToJSON(json: any): AvmKeyValue {
    return AvmKeyValueToJSONTyped(json, false);
}

export function AvmKeyValueToJSONTyped(value?: AvmKeyValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': AvmValueToJSON(value['value']),
    };
}

