/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents an AVM value.
 * @export
 * @interface AvmValue
 */
export interface AvmValue {
    /**
     * value type. Value `1` refers to **bytes**, value `2` refers to **uint64**
     * @type {number}
     * @memberof AvmValue
     */
    type: number;
    /**
     * bytes value.
     * @type {string}
     * @memberof AvmValue
     */
    bytes?: string;
    /**
     * uint value.
     * @type {number}
     * @memberof AvmValue
     */
    uint?: number;
}

/**
 * Check if a given object implements the AvmValue interface.
 */
export function instanceOfAvmValue(value: object): value is AvmValue {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function AvmValueFromJSON(json: any): AvmValue {
    return AvmValueFromJSONTyped(json, false);
}

export function AvmValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvmValue {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'bytes': json['bytes'] == null ? undefined : json['bytes'],
        'uint': json['uint'] == null ? undefined : json['uint'],
    };
}

export function AvmValueToJSON(json: any): AvmValue {
    return AvmValueToJSONTyped(json, false);
}

export function AvmValueToJSONTyped(value?: AvmValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'bytes': value['bytes'],
        'uint': value['uint'],
    };
}

