/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Box name and its content.
 * @export
 * @interface Box
 */
export interface Box {
    /**
     * The round for which this information is relevant
     * @type {number}
     * @memberof Box
     */
    round?: number;
    /**
     * The box name, base64 encoded
     * @type {string}
     * @memberof Box
     */
    name: string;
    /**
     * The box value, base64 encoded.
     * @type {string}
     * @memberof Box
     */
    value: string;
}

/**
 * Check if a given object implements the Box interface.
 */
export function instanceOfBox(value: object): value is Box {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function BoxFromJSON(json: any): Box {
    return BoxFromJSONTyped(json, false);
}

export function BoxFromJSONTyped(json: any, ignoreDiscriminator: boolean): Box {
    if (json == null) {
        return json;
    }
    return {
        
        'round': json['round'] == null ? undefined : json['round'],
        'name': json['name'],
        'value': json['value'],
    };
}

export function BoxToJSON(json: any): Box {
    return BoxToJSONTyped(json, false);
}

export function BoxToJSONTyped(value?: Box | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'round': value['round'],
        'name': value['name'],
        'value': value['value'],
    };
}

