/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * algod mutex and blocking profiling state.
 * @export
 * @interface DebugSettingsProf
 */
export interface DebugSettingsProf {
    /**
     * The rate of blocking events. The profiler aims to sample an average of one blocking event per rate nanoseconds spent blocked. To turn off profiling entirely, pass rate 0.
     * @type {number}
     * @memberof DebugSettingsProf
     */
    blockRate?: number;
    /**
     * The rate of mutex events. On average 1/rate events are reported. To turn off profiling entirely, pass rate 0
     * @type {number}
     * @memberof DebugSettingsProf
     */
    mutexRate?: number;
}

/**
 * Check if a given object implements the DebugSettingsProf interface.
 */
export function instanceOfDebugSettingsProf(value: object): value is DebugSettingsProf {
    return true;
}

export function DebugSettingsProfFromJSON(json: any): DebugSettingsProf {
    return DebugSettingsProfFromJSONTyped(json, false);
}

export function DebugSettingsProfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebugSettingsProf {
    if (json == null) {
        return json;
    }
    return {
        
        'blockRate': json['block-rate'] == null ? undefined : json['block-rate'],
        'mutexRate': json['mutex-rate'] == null ? undefined : json['mutex-rate'],
    };
}

export function DebugSettingsProfToJSON(json: any): DebugSettingsProf {
    return DebugSettingsProfToJSONTyped(json, false);
}

export function DebugSettingsProfToJSONTyped(value?: DebugSettingsProf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'block-rate': value['blockRate'],
        'mutex-rate': value['mutexRate'],
    };
}

