/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EvalDelta } from './EvalDelta';
import {
    EvalDeltaFromJSON,
    EvalDeltaFromJSONTyped,
    EvalDeltaToJSON,
    EvalDeltaToJSONTyped,
} from './EvalDelta';

/**
 * Key-value pairs for StateDelta.
 * @export
 * @interface EvalDeltaKeyValue
 */
export interface EvalDeltaKeyValue {
    /**
     * 
     * @type {string}
     * @memberof EvalDeltaKeyValue
     */
    key: string;
    /**
     * 
     * @type {EvalDelta}
     * @memberof EvalDeltaKeyValue
     */
    value: EvalDelta;
}

/**
 * Check if a given object implements the EvalDeltaKeyValue interface.
 */
export function instanceOfEvalDeltaKeyValue(value: object): value is EvalDeltaKeyValue {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function EvalDeltaKeyValueFromJSON(json: any): EvalDeltaKeyValue {
    return EvalDeltaKeyValueFromJSONTyped(json, false);
}

export function EvalDeltaKeyValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvalDeltaKeyValue {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': EvalDeltaFromJSON(json['value']),
    };
}

export function EvalDeltaKeyValueToJSON(json: any): EvalDeltaKeyValue {
    return EvalDeltaKeyValueToJSONTyped(json, false);
}

export function EvalDeltaKeyValueToJSONTyped(value?: EvalDeltaKeyValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': EvalDeltaToJSON(value['value']),
    };
}

