/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetBlockHash200Response
 */
export interface GetBlockHash200Response {
    /**
     * Block header hash.
     * @type {string}
     * @memberof GetBlockHash200Response
     */
    blockHash: string;
}

/**
 * Check if a given object implements the GetBlockHash200Response interface.
 */
export function instanceOfGetBlockHash200Response(value: object): value is GetBlockHash200Response {
    if (!('blockHash' in value) || value['blockHash'] === undefined) return false;
    return true;
}

export function GetBlockHash200ResponseFromJSON(json: any): GetBlockHash200Response {
    return GetBlockHash200ResponseFromJSONTyped(json, false);
}

export function GetBlockHash200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBlockHash200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'blockHash': json['blockHash'],
    };
}

export function GetBlockHash200ResponseToJSON(json: any): GetBlockHash200Response {
    return GetBlockHash200ResponseToJSONTyped(json, false);
}

export function GetBlockHash200ResponseToJSONTyped(value?: GetBlockHash200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'blockHash': value['blockHash'],
    };
}

