/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppCallLogs } from './AppCallLogs';
import {
    AppCallLogsFromJSON,
    AppCallLogsFromJSONTyped,
    AppCallLogsToJSON,
    AppCallLogsToJSONTyped,
} from './AppCallLogs';

/**
 * 
 * @export
 * @interface GetBlockLogs200Response
 */
export interface GetBlockLogs200Response {
    /**
     * 
     * @type {Array<AppCallLogs>}
     * @memberof GetBlockLogs200Response
     */
    logs: Array<AppCallLogs>;
}

/**
 * Check if a given object implements the GetBlockLogs200Response interface.
 */
export function instanceOfGetBlockLogs200Response(value: object): value is GetBlockLogs200Response {
    if (!('logs' in value) || value['logs'] === undefined) return false;
    return true;
}

export function GetBlockLogs200ResponseFromJSON(json: any): GetBlockLogs200Response {
    return GetBlockLogs200ResponseFromJSONTyped(json, false);
}

export function GetBlockLogs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBlockLogs200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'logs': ((json['logs'] as Array<any>).map(AppCallLogsFromJSON)),
    };
}

export function GetBlockLogs200ResponseToJSON(json: any): GetBlockLogs200Response {
    return GetBlockLogs200ResponseToJSONTyped(json, false);
}

export function GetBlockLogs200ResponseToJSONTyped(value?: GetBlockLogs200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logs': ((value['logs'] as Array<any>).map(AppCallLogsToJSON)),
    };
}

