/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * PendingTransactions is an array of signed transactions exactly as they were submitted.
 * @export
 * @interface GetPendingTransactionsByAddress200Response
 */
export interface GetPendingTransactionsByAddress200Response {
    /**
     * An array of signed transaction objects.
     * @type {Array<object>}
     * @memberof GetPendingTransactionsByAddress200Response
     */
    topTransactions: Array<object>;
    /**
     * Total number of transactions in the pool.
     * @type {number}
     * @memberof GetPendingTransactionsByAddress200Response
     */
    totalTransactions: number;
}

/**
 * Check if a given object implements the GetPendingTransactionsByAddress200Response interface.
 */
export function instanceOfGetPendingTransactionsByAddress200Response(value: object): value is GetPendingTransactionsByAddress200Response {
    if (!('topTransactions' in value) || value['topTransactions'] === undefined) return false;
    if (!('totalTransactions' in value) || value['totalTransactions'] === undefined) return false;
    return true;
}

export function GetPendingTransactionsByAddress200ResponseFromJSON(json: any): GetPendingTransactionsByAddress200Response {
    return GetPendingTransactionsByAddress200ResponseFromJSONTyped(json, false);
}

export function GetPendingTransactionsByAddress200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPendingTransactionsByAddress200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'topTransactions': json['top-transactions'],
        'totalTransactions': json['total-transactions'],
    };
}

export function GetPendingTransactionsByAddress200ResponseToJSON(json: any): GetPendingTransactionsByAddress200Response {
    return GetPendingTransactionsByAddress200ResponseToJSONTyped(json, false);
}

export function GetPendingTransactionsByAddress200ResponseToJSONTyped(value?: GetPendingTransactionsByAddress200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'top-transactions': value['topTransactions'],
        'total-transactions': value['totalTransactions'],
    };
}

