/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RawTransaction200Response
 */
export interface RawTransaction200Response {
    /**
     * encoding of the transaction hash.
     * @type {string}
     * @memberof RawTransaction200Response
     */
    txId: string;
}

/**
 * Check if a given object implements the RawTransaction200Response interface.
 */
export function instanceOfRawTransaction200Response(value: object): value is RawTransaction200Response {
    if (!('txId' in value) || value['txId'] === undefined) return false;
    return true;
}

export function RawTransaction200ResponseFromJSON(json: any): RawTransaction200Response {
    return RawTransaction200ResponseFromJSONTyped(json, false);
}

export function RawTransaction200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawTransaction200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'txId': json['txId'],
    };
}

export function RawTransaction200ResponseToJSON(json: any): RawTransaction200Response {
    return RawTransaction200ResponseToJSONTyped(json, false);
}

export function RawTransaction200ResponseToJSONTyped(value?: RawTransaction200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'txId': value['txId'],
    };
}

