/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A transaction group to simulate.
 * @export
 * @interface SimulateRequestTransactionGroup
 */
export interface SimulateRequestTransactionGroup {
    /**
     * An atomic transaction group.
     * @type {Array<string>}
     * @memberof SimulateRequestTransactionGroup
     */
    txns: Array<string>;
}

/**
 * Check if a given object implements the SimulateRequestTransactionGroup interface.
 */
export function instanceOfSimulateRequestTransactionGroup(value: object): value is SimulateRequestTransactionGroup {
    if (!('txns' in value) || value['txns'] === undefined) return false;
    return true;
}

export function SimulateRequestTransactionGroupFromJSON(json: any): SimulateRequestTransactionGroup {
    return SimulateRequestTransactionGroupFromJSONTyped(json, false);
}

export function SimulateRequestTransactionGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulateRequestTransactionGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'txns': json['txns'],
    };
}

export function SimulateRequestTransactionGroupToJSON(json: any): SimulateRequestTransactionGroup {
    return SimulateRequestTransactionGroupToJSONTyped(json, false);
}

export function SimulateRequestTransactionGroupToJSONTyped(value?: SimulateRequestTransactionGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'txns': value['txns'],
    };
}

