/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApplicationInitialStates } from './ApplicationInitialStates';
import {
    ApplicationInitialStatesFromJSON,
    ApplicationInitialStatesFromJSONTyped,
    ApplicationInitialStatesToJSON,
    ApplicationInitialStatesToJSONTyped,
} from './ApplicationInitialStates';

/**
 * Initial states of resources that were accessed during simulation.
 * @export
 * @interface SimulateInitialStates
 */
export interface SimulateInitialStates {
    /**
     * The initial states of accessed application before simulation. The order of this array is arbitrary.
     * @type {Array<ApplicationInitialStates>}
     * @memberof SimulateInitialStates
     */
    appInitialStates?: Array<ApplicationInitialStates>;
}

/**
 * Check if a given object implements the SimulateInitialStates interface.
 */
export function instanceOfSimulateInitialStates(value: object): value is SimulateInitialStates {
    return true;
}

export function SimulateInitialStatesFromJSON(json: any): SimulateInitialStates {
    return SimulateInitialStatesFromJSONTyped(json, false);
}

export function SimulateInitialStatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulateInitialStates {
    if (json == null) {
        return json;
    }
    return {
        
        'appInitialStates': json['app-initial-states'] == null ? undefined : ((json['app-initial-states'] as Array<any>).map(ApplicationInitialStatesFromJSON)),
    };
}

export function SimulateInitialStatesToJSON(json: any): SimulateInitialStates {
    return SimulateInitialStatesToJSONTyped(json, false);
}

export function SimulateInitialStatesToJSONTyped(value?: SimulateInitialStates | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app-initial-states': value['appInitialStates'] == null ? undefined : ((value['appInitialStates'] as Array<any>).map(ApplicationInitialStatesToJSON)),
    };
}

