/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TealDisassemble200Response
 */
export interface TealDisassemble200Response {
    /**
     * disassembled Teal code
     * @type {string}
     * @memberof TealDisassemble200Response
     */
    result: string;
}

/**
 * Check if a given object implements the TealDisassemble200Response interface.
 */
export function instanceOfTealDisassemble200Response(value: object): value is TealDisassemble200Response {
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function TealDisassemble200ResponseFromJSON(json: any): TealDisassemble200Response {
    return TealDisassemble200ResponseFromJSONTyped(json, false);
}

export function TealDisassemble200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TealDisassemble200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'],
    };
}

export function TealDisassemble200ResponseToJSON(json: any): TealDisassemble200Response {
    return TealDisassemble200ResponseToJSONTyped(json, false);
}

export function TealDisassemble200ResponseToJSONTyped(value?: TealDisassemble200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
    };
}

