/* tslint:disable */
/* eslint-disable */
/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TealValue } from './TealValue';
import {
    TealValueFromJSON,
    TealValueFromJSONTyped,
    TealValueToJSON,
    TealValueToJSONTyped,
} from './TealValue';

/**
 * Represents a key-value pair in an application store.
 * @export
 * @interface TealKeyValue
 */
export interface TealKeyValue {
    /**
     * 
     * @type {string}
     * @memberof TealKeyValue
     */
    key: string;
    /**
     * 
     * @type {TealValue}
     * @memberof TealKeyValue
     */
    value: TealValue;
}

/**
 * Check if a given object implements the TealKeyValue interface.
 */
export function instanceOfTealKeyValue(value: object): value is TealKeyValue {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function TealKeyValueFromJSON(json: any): TealKeyValue {
    return TealKeyValueFromJSONTyped(json, false);
}

export function TealKeyValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): TealKeyValue {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': TealValueFromJSON(json['value']),
    };
}

export function TealKeyValueToJSON(json: any): TealKeyValue {
    return TealKeyValueToJSONTyped(json, false);
}

export function TealKeyValueToJSONTyped(value?: TealKeyValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': TealValueToJSON(value['value']),
    };
}

