[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "wheel"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "algokit_utils"
version = "0.1.0"
description = ""
packages = [
    { include = "algokit_utils" }
]
include = [
    { path = "algokit_utils/*.so", format = "wheel" },
    { path = "algokit_utils/*.dll", format = "wheel" },
    { path = "algokit_utils/*.dylib", format = "wheel" }
]
