[bindings.python]
cdylib_name = "algokit_msgpack_ffi"
package_name = "algokit_msgpack"

[bindings.kotlin]
cdylib_name = "algokit_msgpack_ffi"
package_name = "com.algorand.algokit.msgpack"

[bindings.swift]
cdylib_name = "algokit_msgpack_ffi"
module_name = "AlgokitMsgpack"
