# coding: utf-8

"""
    Algod REST API.

    API endpoint for algod operations.

    The version of the OpenAPI document: 0.0.1
    Contact: contact@algorand.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import pytest
import os
import json
from typing import Dict, Any
import os.path

from algorand_algod_client.configuration import Configuration
from algorand_algod_client.api_client import ApiClient
from test.test_utils import TestDataGenerator


@pytest.fixture
def base_configuration():
    """Fixture to create a base configuration for tests."""
    # Default values for local Algorand node
    host = os.environ.get("ALGORAND_HOST", "http://localhost:4001")
    
    configuration = Configuration(
        host=host
    )
    
    # Configure API key authorization
    api_key = os.environ.get(
        "ALGORAND_API_TOKEN", 
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    )
    configuration.api_key['X-Algo-API-Token'] = api_key
    
    return configuration


@pytest.fixture
def api_client_fixture(base_configuration):
    """Fixture to create a configured API client."""
    client = ApiClient(configuration=base_configuration)
    yield client
    # No cleanup needed for non-async client
