/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::Wallet;

/// CreateWalletResponse is the response to `POST /v1/wallet`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct CreateWalletResponse {
    #[serde(rename = "wallet")]
    pub wallet: Wallet,
}

impl CreateWalletResponse {
    /// Constructor for CreateWalletResponse
    pub fn new(wallet: Wallet) -> CreateWalletResponse {
        CreateWalletResponse { wallet }
    }
}
