/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact::Address;
use serde::{Deserialize, Serialize};

/// The request for `DELETE /v1/multisig`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct DeleteMultisigRequest {
    #[serde(rename = "address")]
    pub address: Address,
    #[serde(rename = "wallet_handle_token")]
    pub wallet_handle_token: String,
    #[serde(rename = "wallet_password", skip_serializing_if = "Option::is_none")]
    pub wallet_password: Option<String>,
}

impl DeleteMultisigRequest {
    /// Constructor for DeleteMultisigRequest
    pub fn new(address: Address, wallet_handle_token: String) -> DeleteMultisigRequest {
        DeleteMultisigRequest {
            address,
            wallet_handle_token,
            wallet_password: None,
        }
    }
}
