/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::PublicKey;

/// ExportMultisigResponse is the response to `POST /v1/multisig/export`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct ExportMultisigResponse {
    #[serde(rename = "multisig_version")]
    pub multisig_version: u8,
    #[serde(rename = "pks")]
    pub public_keys: Vec<PublicKey>,
    #[serde(rename = "threshold")]
    pub threshold: u8,
}

impl ExportMultisigResponse {
    /// Constructor for ExportMultisigResponse
    pub fn new(
        multisig_version: u8,
        public_keys: Vec<PublicKey>,
        threshold: u8,
    ) -> ExportMultisigResponse {
        ExportMultisigResponse {
            multisig_version,
            public_keys,
            threshold,
        }
    }
}
