/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::MasterDerivationKey;

/// ExportMasterKeyResponse is the response to `POST /v1/master-key/export`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct ExportMasterKeyResponse {
    #[serde(rename = "master_derivation_key")]
    pub master_derivation_key: MasterDerivationKey,
}

impl ExportMasterKeyResponse {
    /// Constructor for ExportMasterKeyResponse
    pub fn new(master_derivation_key: MasterDerivationKey) -> ExportMasterKeyResponse {
        ExportMasterKeyResponse {
            master_derivation_key,
        }
    }
}
