/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::PublicKey;

/// The request for `POST /v1/multisig/import`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct ImportMultisigRequest {
    #[serde(rename = "multisig_version")]
    pub multisig_version: u8,
    #[serde(rename = "pks")]
    pub public_keys: Vec<PublicKey>,
    #[serde(rename = "threshold")]
    pub threshold: u8,
    #[serde(rename = "wallet_handle_token")]
    pub wallet_handle_token: String,
}

impl ImportMultisigRequest {
    /// Constructor for ImportMultisigRequest
    pub fn new(
        multisig_version: u8,
        public_keys: Vec<PublicKey>,
        threshold: u8,
        wallet_handle_token: String,
    ) -> ImportMultisigRequest {
        ImportMultisigRequest {
            multisig_version,
            public_keys,
            threshold,
            wallet_handle_token,
        }
    }
}
