/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_with::{Bytes, serde_as};

/// The request for `POST /v1/key/import`
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct ImportKeyRequest {
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "private_key")]
    pub private_key: Vec<u8>,
    #[serde(rename = "wallet_handle_token")]
    pub wallet_handle_token: String,
}

impl ImportKeyRequest {
    /// Constructor for ImportKeyRequest
    pub fn new(private_key: Vec<u8>, wallet_handle_token: String) -> ImportKeyRequest {
        ImportKeyRequest {
            private_key,
            wallet_handle_token,
        }
    }
}
