/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact::Address;
use serde::{Deserialize, Serialize};

/// ImportMultisigResponse is the response to `POST /v1/multisig/import`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct ImportMultisigResponse {
    #[serde(rename = "address")]
    pub address: Address,
}

impl ImportMultisigResponse {
    /// Constructor for ImportMultisigResponse
    pub fn new(address: Address) -> ImportMultisigResponse {
        ImportMultisigResponse { address }
    }
}
