/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InitWalletHandleTokenResponse is the response to `POST /v1/wallet/init`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct InitWalletHandleTokenResponse {
    #[serde(rename = "wallet_handle_token")]
    pub wallet_handle_token: String,
}

impl InitWalletHandleTokenResponse {
    /// Constructor for InitWalletHandleTokenResponse
    pub fn new(wallet_handle_token: String) -> InitWalletHandleTokenResponse {
        InitWalletHandleTokenResponse {
            wallet_handle_token,
        }
    }
}
