/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// The request for `POST /v1/wallet/init`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct InitWalletHandleTokenRequest {
    #[serde(rename = "wallet_id")]
    pub wallet_id: String,
    #[serde(rename = "wallet_password")]
    pub wallet_password: String,
}

impl InitWalletHandleTokenRequest {
    /// Constructor for InitWalletHandleTokenRequest
    pub fn new(wallet_id: String, wallet_password: String) -> InitWalletHandleTokenRequest {
        InitWalletHandleTokenRequest {
            wallet_id,
            wallet_password,
        }
    }
}
