/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListMultisigResponse is the response to `POST /v1/multisig/list`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct ListMultisigResponse {
    #[serde(rename = "addresses")]
    pub addresses: Vec<String>,
}

impl ListMultisigResponse {
    /// Constructor for ListMultisigResponse
    pub fn new(addresses: Vec<String>) -> ListMultisigResponse {
        ListMultisigResponse { addresses }
    }
}
