/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::Wallet;

/// ListWalletsResponse is the response to `GET /v1/wallets`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct ListWalletsResponse {
    #[serde(rename = "wallets")]
    pub wallets: Vec<Wallet>,
}

impl ListWalletsResponse {
    /// Constructor for ListWalletsResponse
    pub fn new(wallets: Vec<Wallet>) -> ListWalletsResponse {
        ListWalletsResponse { wallets }
    }
}
