/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_with::{Bytes, serde_as};

/// SignProgramResponse is the response to `POST /v1/data/sign`
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct SignProgramResponse {
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "sig")]
    pub sig: Vec<u8>,
}

impl SignProgramResponse {
    /// Constructor for SignProgramResponse
    pub fn new(sig: Vec<u8>) -> SignProgramResponse {
        SignProgramResponse { sig }
    }
}
