/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_with::{Bytes, serde_as};

/// SignProgramMultisigResponse is the response to `POST /v1/multisig/signdata`
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct SignProgramMultisigResponse {
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "multisig")]
    pub multisig: Vec<u8>,
}

impl SignProgramMultisigResponse {
    /// Constructor for SignProgramMultisigResponse
    pub fn new(multisig: Vec<u8>) -> SignProgramMultisigResponse {
        SignProgramMultisigResponse { multisig }
    }
}
