/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_with::{Bytes, serde_as};

use crate::models::Digest;
use crate::models::MultisigSig;
use crate::models::PublicKey;

/// The request for `POST /v1/multisig/sign`
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct SignMultisigTxnRequest {
    #[serde(rename = "partial_multisig", skip_serializing_if = "Option::is_none")]
    pub partial_multisig: Option<MultisigSig>,
    #[serde(rename = "public_key")]
    pub public_key: PublicKey,
    #[serde(rename = "signer", skip_serializing_if = "Option::is_none")]
    pub signer: Option<Digest>,
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "transaction")]
    pub transaction: Vec<u8>,
    #[serde(rename = "wallet_handle_token")]
    pub wallet_handle_token: String,
    #[serde(rename = "wallet_password", skip_serializing_if = "Option::is_none")]
    pub wallet_password: Option<String>,
}

impl SignMultisigTxnRequest {
    /// Constructor for SignMultisigTxnRequest
    pub fn new(
        public_key: PublicKey,
        transaction: Vec<u8>,
        wallet_handle_token: String,
    ) -> SignMultisigTxnRequest {
        SignMultisigTxnRequest {
            public_key,
            transaction,
            wallet_handle_token,
            partial_multisig: None,
            signer: None,
            wallet_password: None,
        }
    }
}
