/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::Wallet;

/// WalletHandle includes the wallet the handle corresponds to
/// and the number of number of seconds to expiration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct WalletHandle {
    #[serde(rename = "expires_seconds")]
    pub expires_seconds: u64,
    #[serde(rename = "wallet")]
    pub wallet: Wallet,
}

impl WalletHandle {
    /// Constructor for WalletHandle
    pub fn new(expires_seconds: u64, wallet: Wallet) -> WalletHandle {
        WalletHandle {
            expires_seconds,
            wallet,
        }
    }
}
