/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::WalletHandle;

/// WalletInfoResponse is the response to `POST /v1/wallet/info`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct WalletInfoResponse {
    #[serde(rename = "wallet_handle")]
    pub wallet_handle: WalletHandle,
}

impl WalletInfoResponse {
    /// Constructor for WalletInfoResponse
    pub fn new(wallet_handle: WalletHandle) -> WalletInfoResponse {
        WalletInfoResponse { wallet_handle }
    }
}
