/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::TxType;

/// Wallet is the API's representation of a wallet
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct Wallet {
    #[serde(rename = "driver_name")]
    pub driver_name: String,
    #[serde(rename = "driver_version")]
    pub driver_version: u32,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "mnemonic_ux")]
    pub mnemonic_ux: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "supported_txs")]
    pub supported_txs: Vec<TxType>,
}

impl Wallet {
    /// Constructor for Wallet
    pub fn new(
        driver_name: String,
        driver_version: u32,
        id: String,
        mnemonic_ux: bool,
        name: String,
        supported_txs: Vec<TxType>,
    ) -> Wallet {
        Wallet {
            driver_name,
            driver_version,
            id,
            mnemonic_ux,
            name,
            supported_txs,
        }
    }
}
