templateDir: oas_templates/typescript
additionalProperties:
  npmVersion: 0.0.1
  npmName: "@algorandfoundation/algokit-algod-api"
  supportsES6: true
  useRxJS: false
  platform: browser
openapiNormalizer:
  SET_TAGS_FOR_ALL_OPERATIONS: Algod

files:
  # Section for dropping custom tests
  tsconfig.esm.mustache:
    templateType: SupportingFiles
    destinationFilename: tsconfig.esm.json
  tsconfig.cjs.mustache:
    templateType: SupportingFiles
    destinationFilename: tsconfig.cjs.json
  bigint-utils.mustache:
    templateType: SupportingFiles
    destinationFilename: bigint-utils.ts
  .npmrc.mustache:
    templateType: SupportingFiles
    destinationFilename: .npmrc
  custom_tests/transactions.test.mustache:
    templateType: SupportingFiles
    destinationFilename: tests/transactions.test.ts
  custom_tests/accounts.test.mustache:
    templateType: SupportingFiles
    destinationFilename: tests/accounts.test.ts
  custom_tests/artifacts/dummy_app.arc56.mustache:
    templateType: SupportingFiles
    destinationFilename: tests/artifacts/dummy_app.arc56.json
