/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::AssetHolding;
use crate::models::AssetParams;

/// AccountAssetResponse describes the account's asset holding and asset parameters (if either exist) for a specific asset ID. Asset parameters will only be returned if the provided address is the asset's creator.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct AccountAssetInformation {
    /// The round for which this information is relevant.
    #[serde(rename = "round")]
    pub round: u64,
    #[serde(rename = "asset-holding", skip_serializing_if = "Option::is_none")]
    pub asset_holding: Option<AssetHolding>,
    #[serde(rename = "created-asset", skip_serializing_if = "Option::is_none")]
    pub created_asset: Option<AssetParams>,
}

impl AccountAssetInformation {
    /// Constructor for AccountAssetInformation
    pub fn new(round: u64) -> AccountAssetInformation {
        AccountAssetInformation {
            round,
            asset_holding: None,
            created_asset: None,
        }
    }
}
