/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct BlockTxidsResponse {
    /// Block transaction IDs.
    #[serde(rename = "blockTxids")]
    pub block_tx_ids: Vec<String>,
}

impl BlockTxidsResponse {
    /// Constructor for BlockTxidsResponse
    pub fn new(block_tx_ids: Vec<String>) -> BlockTxidsResponse {
        BlockTxidsResponse { block_tx_ids }
    }
}
