/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::AppCallLogs;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct BlockLogsResponse {
    #[serde(rename = "logs")]
    pub logs: Vec<AppCallLogs>,
}

impl BlockLogsResponse {
    /// Constructor for BlockLogsResponse
    pub fn new(logs: Vec<AppCallLogs>) -> BlockLogsResponse {
        BlockLogsResponse { logs }
    }
}
