/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct BlockHashResponse {
    /// Block header hash.
    #[serde(rename = "blockHash")]
    pub block_hash: String,
}

impl BlockHashResponse {
    /// Constructor for BlockHashResponse
    pub fn new(block_hash: String) -> BlockHashResponse {
        BlockHashResponse { block_hash }
    }
}
