/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::BoxDescriptor;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct BoxesResponse {
    #[serde(rename = "boxes")]
    pub boxes: Vec<BoxDescriptor>,
}

impl BoxesResponse {
    /// Constructor for BoxesResponse
    pub fn new(boxes: Vec<BoxDescriptor>) -> BoxesResponse {
        BoxesResponse { boxes }
    }
}
