/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// An catchpoint start response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct CatchpointStartResponse {
    /// Catchup start response string
    #[serde(rename = "catchup-message")]
    pub catchup_message: String,
}

impl CatchpointStartResponse {
    /// Constructor for CatchpointStartResponse
    pub fn new(catchup_message: String) -> CatchpointStartResponse {
        CatchpointStartResponse { catchup_message }
    }
}
