/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct GetBlockTimeStampOffsetResponse {
    /// Timestamp offset in seconds.
    #[serde(rename = "offset")]
    pub offset: u64,
}

impl GetBlockTimeStampOffsetResponse {
    /// Constructor for GetBlockTimeStampOffsetResponse
    pub fn new(offset: u64) -> GetBlockTimeStampOffsetResponse {
        GetBlockTimeStampOffsetResponse { offset }
    }
}
