/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct PostParticipationResponse {
    /// encoding of the participation ID.
    #[serde(rename = "partId")]
    pub part_id: String,
}

impl PostParticipationResponse {
    /// Constructor for PostParticipationResponse
    pub fn new(part_id: String) -> PostParticipationResponse {
        PostParticipationResponse { part_id }
    }
}
