/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Source map for the program
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct SourceMap {
    #[serde(rename = "version")]
    pub version: u64,
    /// A list of original sources used by the "mappings" entry.
    #[serde(rename = "sources")]
    pub sources: Vec<String>,
    /// A list of symbol names used by the "mappings" entry.
    #[serde(rename = "names")]
    pub names: Vec<String>,
    /// A string with the encoded mapping data.
    #[serde(rename = "mappings")]
    pub mappings: String,
}

impl SourceMap {
    /// Constructor for SourceMap
    pub fn new(
        version: u64,
        sources: Vec<String>,
        names: Vec<String>,
        mappings: String,
    ) -> SourceMap {
        SourceMap {
            version,
            sources,
            names,
            mappings,
        }
    }
}
