/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[cfg(feature = "ffi_wasm")]
use wasm_bindgen::prelude::wasm_bindgen;

/// AbortCatchup200Response : An catchpoint abort response.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "ffi_wasm", tsify(into_wasm_abi, from_wasm_abi))]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct AbortCatchup200Response {
    /// Catchup abort response string
    #[serde(rename = "catchup-message")]
    
    
    
    pub catchup_message: String,
}

impl AbortCatchup200Response {
    /// An catchpoint abort response.
    #[cfg_attr(feature = "ffi_uniffi", uniffi::constructor)]
    pub fn new(
        catchup_message: String,
    ) -> AbortCatchup200Response {
        AbortCatchup200Response {
            catchup_message: catchup_message,
        }
    }
}



impl crate::JsonSerializable for AbortCatchup200Response {}


crate::auto_impl_json_ffi!(AbortCatchup200Response, abort_catchup200_response);

