/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApplicationLocalReference : References an account's local state for an application.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "ffi_wasm", tsify(into_wasm_abi, from_wasm_abi))]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct ApplicationLocalReference {
    /// Address of the account with the local state.
    #[serde(rename = "account")]
    
    
    
    pub account: String,
    /// Application ID of the local state application.
    #[serde(rename = "app")]
    
    
    
    pub app: i32,
}

impl ApplicationLocalReference {
    /// References an account's local state for an application.
    pub fn new(account: String, app: i32) -> ApplicationLocalReference {
        ApplicationLocalReference {
            account,
            app,
        }
    }
}

impl crate::JsonSerializable for ApplicationLocalReference {}

impl crate::MsgpackDecodable for ApplicationLocalReference {}

