/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

/// ApplicationParams : Stores the global information associated with an application.
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "ffi_wasm", tsify(into_wasm_abi, from_wasm_abi))]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct ApplicationParams {
    /// The address that created this application. This is the address where the parameters and global state for this application can be found.
    #[serde(rename = "creator")]
    
    
    
    pub creator: String,
    /// \\[approv\\] approval program.
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "approval-program")]
    
    
    
    pub approval_program: Vec<u8>,
    /// \\[clearp\\] approval program.
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "clear-state-program")]
    
    
    
    pub clear_state_program: Vec<u8>,
    /// \\[epp\\] the amount of extra program pages available to this app.
    #[serde(rename = "extra-program-pages", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub extra_program_pages: Option<i32>,
    #[serde(rename = "local-state-schema", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub local_state_schema: Option<models::ApplicationStateSchema>,
    #[serde(rename = "global-state-schema", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub global_state_schema: Option<models::ApplicationStateSchema>,
    /// Represents a key-value store for use in an application.
    #[serde(rename = "global-state", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub global_state: Option<Vec<models::TealKeyValue>>,
}

impl ApplicationParams {
    /// Stores the global information associated with an application.
    #[cfg_attr(feature = "ffi_uniffi", uniffi::constructor)]
    #[cfg_attr(feature = "ffi_wasm", wasm_bindgen(constructor))]
    pub fn new(
        creator: String,approval_program: Vec<u8>,clear_state_program: Vec<u8>, extra_program_pages: Option<i32>, local_state_schema: Option<models::ApplicationStateSchema>, global_state_schema: Option<models::ApplicationStateSchema>, global_state: Option<Vec<models::TealKeyValue>>
    ) -> ApplicationParams {
        ApplicationParams {
            creator: creator,
            approval_program: approval_program,
            clear_state_program: clear_state_program,
            extra_program_pages: extra_program_pages,
            local_state_schema: local_state_schema,
            global_state_schema: global_state_schema,
            global_state: global_state,
        }
    }
}

impl crate::JsonSerializable for ApplicationParams {}

impl crate::MsgpackEncodable for ApplicationParams {}
impl crate::MsgpackDecodable for ApplicationParams {}

