/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DebugSettingsProf : algod mutex and blocking profiling state.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "ffi_wasm", tsify(into_wasm_abi, from_wasm_abi))]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct DebugSettingsProf {
    /// The rate of blocking events. The profiler aims to sample an average of one blocking event per rate nanoseconds spent blocked. To turn off profiling entirely, pass rate 0.
    #[serde(rename = "block-rate", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub block_rate: Option<i32>,
    /// The rate of mutex events. On average 1/rate events are reported. To turn off profiling entirely, pass rate 0
    #[serde(rename = "mutex-rate", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub mutex_rate: Option<i32>,
}

impl DebugSettingsProf {
    /// algod mutex and blocking profiling state.
    #[cfg_attr(feature = "ffi_uniffi", uniffi::constructor)]
    #[cfg_attr(feature = "ffi_wasm", wasm_bindgen(constructor))]
    pub fn new(
         block_rate: Option<i32>, mutex_rate: Option<i32>
    ) -> DebugSettingsProf {
        DebugSettingsProf {
            block_rate: block_rate,
            mutex_rate: mutex_rate,
        }
    }
}

impl crate::JsonSerializable for DebugSettingsProf {}


