/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "ffi_wasm", tsify(into_wasm_abi, from_wasm_abi))]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct GetBlockTxids200Response {
    /// Block transaction IDs.
    #[serde(rename = "blockTxids")]
    
    
    
    pub block_txids: Vec<String>,
}

impl GetBlockTxids200Response {
    #[cfg_attr(feature = "ffi_uniffi", uniffi::constructor)]
    #[cfg_attr(feature = "ffi_wasm", wasm_bindgen(constructor))]
    pub fn new(
        block_txids: Vec<String>,
    ) -> GetBlockTxids200Response {
        GetBlockTxids200Response {
            block_txids: block_txids,
        }
    }
}

impl crate::JsonSerializable for GetBlockTxids200Response {}


