/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[cfg(feature = "ffi_wasm")]
use wasm_bindgen::prelude::wasm_bindgen;




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "ffi_wasm", tsify(into_wasm_abi, from_wasm_abi))]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct GetBlockTimeStampOffset200Response {
    /// Timestamp offset in seconds.
    #[serde(rename = "offset")]
    
    
    
    pub offset: i32,
}

impl GetBlockTimeStampOffset200Response {
    #[cfg_attr(feature = "ffi_uniffi", uniffi::constructor)]
    pub fn new(
        offset: i32,
    ) -> GetBlockTimeStampOffset200Response {
        GetBlockTimeStampOffset200Response {
            offset: offset,
        }
    }
}



impl crate::JsonSerializable for GetBlockTimeStampOffset200Response {}


crate::auto_impl_json_ffi!(GetBlockTimeStampOffset200Response, get_block_time_stamp_offset200_response);

