/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[cfg(feature = "ffi_wasm")]
use wasm_bindgen::prelude::wasm_bindgen;




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "ffi_wasm", tsify(into_wasm_abi, from_wasm_abi))]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct GetSyncRound200Response {
    /// The minimum sync round for the ledger.
    #[serde(rename = "round")]
    
    
    
    pub round: i32,
}

impl GetSyncRound200Response {
    #[cfg_attr(feature = "ffi_uniffi", uniffi::constructor)]
    pub fn new(
        round: i32,
    ) -> GetSyncRound200Response {
        GetSyncRound200Response {
            round: round,
        }
    }
}



impl crate::JsonSerializable for GetSyncRound200Response {}


crate::auto_impl_json_ffi!(GetSyncRound200Response, get_sync_round200_response);

