/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[cfg(feature = "ffi_wasm")]
use wasm_bindgen::prelude::wasm_bindgen;

/// GetStatus200Response : NodeStatus contains the information about a node status



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "ffi_wasm", tsify(into_wasm_abi, from_wasm_abi))]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct GetStatus200Response {
    /// CatchupTime in nanoseconds
    #[serde(rename = "catchup-time")]
    
    
    
    pub catchup_time: i32,
    /// LastRound indicates the last round seen
    #[serde(rename = "last-round")]
    
    
    
    pub last_round: i32,
    /// LastVersion indicates the last consensus version supported
    #[serde(rename = "last-version")]
    
    
    
    pub last_version: String,
    /// NextVersion of consensus protocol to use
    #[serde(rename = "next-version")]
    
    
    
    pub next_version: String,
    /// NextVersionRound is the round at which the next consensus version will apply
    #[serde(rename = "next-version-round")]
    
    
    
    pub next_version_round: i32,
    /// NextVersionSupported indicates whether the next consensus version is supported by this node
    #[serde(rename = "next-version-supported")]
    
    
    
    pub next_version_supported: bool,
    /// StoppedAtUnsupportedRound indicates that the node does not support the new rounds and has stopped making progress
    #[serde(rename = "stopped-at-unsupported-round")]
    
    
    
    pub stopped_at_unsupported_round: bool,
    /// TimeSinceLastRound in nanoseconds
    #[serde(rename = "time-since-last-round")]
    
    
    
    pub time_since_last_round: i32,
    /// The last catchpoint seen by the node
    #[serde(rename = "last-catchpoint", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub last_catchpoint: Option<String>,
    /// The current catchpoint that is being caught up to
    #[serde(rename = "catchpoint", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub catchpoint: Option<String>,
    /// The total number of accounts included in the current catchpoint
    #[serde(rename = "catchpoint-total-accounts", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub catchpoint_total_accounts: Option<i32>,
    /// The number of accounts from the current catchpoint that have been processed so far as part of the catchup
    #[serde(rename = "catchpoint-processed-accounts", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub catchpoint_processed_accounts: Option<i32>,
    /// The number of accounts from the current catchpoint that have been verified so far as part of the catchup
    #[serde(rename = "catchpoint-verified-accounts", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub catchpoint_verified_accounts: Option<i32>,
    /// The total number of key-values (KVs) included in the current catchpoint
    #[serde(rename = "catchpoint-total-kvs", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub catchpoint_total_kvs: Option<i32>,
    /// The number of key-values (KVs) from the current catchpoint that have been processed so far as part of the catchup
    #[serde(rename = "catchpoint-processed-kvs", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub catchpoint_processed_kvs: Option<i32>,
    /// The number of key-values (KVs) from the current catchpoint that have been verified so far as part of the catchup
    #[serde(rename = "catchpoint-verified-kvs", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub catchpoint_verified_kvs: Option<i32>,
    /// The total number of blocks that are required to complete the current catchpoint catchup
    #[serde(rename = "catchpoint-total-blocks", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub catchpoint_total_blocks: Option<i32>,
    /// The number of blocks that have already been obtained by the node as part of the catchup
    #[serde(rename = "catchpoint-acquired-blocks", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub catchpoint_acquired_blocks: Option<i32>,
    /// Upgrade delay
    #[serde(rename = "upgrade-delay", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub upgrade_delay: Option<i32>,
    /// This node's upgrade vote
    #[serde(rename = "upgrade-node-vote", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub upgrade_node_vote: Option<bool>,
    /// Yes votes required for consensus upgrade
    #[serde(rename = "upgrade-votes-required", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub upgrade_votes_required: Option<i32>,
    /// Total votes cast for consensus upgrade
    #[serde(rename = "upgrade-votes", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub upgrade_votes: Option<i32>,
    /// Yes votes cast for consensus upgrade
    #[serde(rename = "upgrade-yes-votes", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub upgrade_yes_votes: Option<i32>,
    /// No votes cast for consensus upgrade
    #[serde(rename = "upgrade-no-votes", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub upgrade_no_votes: Option<i32>,
    /// Next protocol round
    #[serde(rename = "upgrade-next-protocol-vote-before", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub upgrade_next_protocol_vote_before: Option<i32>,
    /// Total voting rounds for current upgrade
    #[serde(rename = "upgrade-vote-rounds", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub upgrade_vote_rounds: Option<i32>,
}

impl GetStatus200Response {
    /// NodeStatus contains the information about a node status
    #[cfg_attr(feature = "ffi_uniffi", uniffi::constructor)]
    pub fn new(
        catchup_time: i32,last_round: i32,last_version: String,next_version: String,next_version_round: i32,next_version_supported: bool,stopped_at_unsupported_round: bool,time_since_last_round: i32, last_catchpoint: Option<String>, catchpoint: Option<String>, catchpoint_total_accounts: Option<i32>, catchpoint_processed_accounts: Option<i32>, catchpoint_verified_accounts: Option<i32>, catchpoint_total_kvs: Option<i32>, catchpoint_processed_kvs: Option<i32>, catchpoint_verified_kvs: Option<i32>, catchpoint_total_blocks: Option<i32>, catchpoint_acquired_blocks: Option<i32>, upgrade_delay: Option<i32>, upgrade_node_vote: Option<bool>, upgrade_votes_required: Option<i32>, upgrade_votes: Option<i32>, upgrade_yes_votes: Option<i32>, upgrade_no_votes: Option<i32>, upgrade_next_protocol_vote_before: Option<i32>, upgrade_vote_rounds: Option<i32>
    ) -> GetStatus200Response {
        GetStatus200Response {
            catchup_time: catchup_time,
            last_round: last_round,
            last_version: last_version,
            next_version: next_version,
            next_version_round: next_version_round,
            next_version_supported: next_version_supported,
            stopped_at_unsupported_round: stopped_at_unsupported_round,
            time_since_last_round: time_since_last_round,
            last_catchpoint: last_catchpoint,
            catchpoint: catchpoint,
            catchpoint_total_accounts: catchpoint_total_accounts,
            catchpoint_processed_accounts: catchpoint_processed_accounts,
            catchpoint_verified_accounts: catchpoint_verified_accounts,
            catchpoint_total_kvs: catchpoint_total_kvs,
            catchpoint_processed_kvs: catchpoint_processed_kvs,
            catchpoint_verified_kvs: catchpoint_verified_kvs,
            catchpoint_total_blocks: catchpoint_total_blocks,
            catchpoint_acquired_blocks: catchpoint_acquired_blocks,
            upgrade_delay: upgrade_delay,
            upgrade_node_vote: upgrade_node_vote,
            upgrade_votes_required: upgrade_votes_required,
            upgrade_votes: upgrade_votes,
            upgrade_yes_votes: upgrade_yes_votes,
            upgrade_no_votes: upgrade_no_votes,
            upgrade_next_protocol_vote_before: upgrade_next_protocol_vote_before,
            upgrade_vote_rounds: upgrade_vote_rounds,
        }
    }
}



impl crate::JsonSerializable for GetStatus200Response {}


crate::auto_impl_json_ffi!(GetStatus200Response, get_status200_response);

