/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[cfg(feature = "ffi_wasm")]
use wasm_bindgen::prelude::wasm_bindgen;




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "ffi_wasm", tsify(into_wasm_abi, from_wasm_abi))]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct GetBlockHash200Response {
    /// Block header hash.
    #[serde(rename = "blockHash")]
    
    
    
    pub block_hash: String,
}

impl GetBlockHash200Response {
    #[cfg_attr(feature = "ffi_uniffi", uniffi::constructor)]
    pub fn new(
        block_hash: String,
    ) -> GetBlockHash200Response {
        GetBlockHash200Response {
            block_hash: block_hash,
        }
    }
}



impl crate::JsonSerializable for GetBlockHash200Response {}


crate::auto_impl_json_ffi!(GetBlockHash200Response, get_block_hash200_response);

