/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[cfg(feature = "ffi_wasm")]
use wasm_bindgen::prelude::wasm_bindgen;




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "ffi_wasm", tsify(into_wasm_abi, from_wasm_abi))]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct RawTransaction200Response {
    /// encoding of the transaction hash.
    #[serde(rename = "txId")]
    
    
    
    pub tx_id: String,
}

impl RawTransaction200Response {
    #[cfg_attr(feature = "ffi_uniffi", uniffi::constructor)]
    pub fn new(
        tx_id: String,
    ) -> RawTransaction200Response {
        RawTransaction200Response {
            tx_id: tx_id,
        }
    }
}



impl crate::JsonSerializable for RawTransaction200Response {}


crate::auto_impl_json_ffi!(RawTransaction200Response, raw_transaction200_response);

