/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScratchChange : A write operation into a scratch slot.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "ffi_wasm", tsify(into_wasm_abi, from_wasm_abi))]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct ScratchChange {
    /// The scratch slot written.
    #[serde(rename = "slot")]
    
    
    
    pub slot: i32,
    #[serde(rename = "new-value")]
    
    
    
    pub new_value: models::AvmValue,
}

impl ScratchChange {
    /// A write operation into a scratch slot.
    pub fn new(slot: i32, new_value: models::AvmValue) -> ScratchChange {
        ScratchChange {
            slot,
            new_value: new_value,
        }
    }
}

impl crate::JsonSerializable for ScratchChange {}

impl crate::MsgpackDecodable for ScratchChange {}

