/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SimulationOpcodeTraceUnit : The set of trace information and effect from evaluating a single opcode.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "ffi_wasm", tsify(into_wasm_abi, from_wasm_abi))]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct SimulationOpcodeTraceUnit {
    /// The program counter of the current opcode being evaluated.
    #[serde(rename = "pc")]
    
    
    
    pub pc: i32,
    /// The writes into scratch slots.
    #[serde(rename = "scratch-changes", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub scratch_changes: Option<Vec<models::ScratchChange>>,
    /// The operations against the current application's states.
    #[serde(rename = "state-changes", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub state_changes: Option<Vec<models::ApplicationStateOperation>>,
    /// The indexes of the traces for inner transactions spawned by this opcode, if any.
    #[serde(rename = "spawned-inners", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub spawned_inners: Option<Vec<i32>>,
    /// The number of deleted stack values by this opcode.
    #[serde(rename = "stack-pop-count", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub stack_pop_count: Option<i32>,
    /// The values added by this opcode to the stack.
    #[serde(rename = "stack-additions", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub stack_additions: Option<Vec<models::AvmValue>>,
}

impl SimulationOpcodeTraceUnit {
    /// The set of trace information and effect from evaluating a single opcode.
    pub fn new(pc: i32) -> SimulationOpcodeTraceUnit {
        SimulationOpcodeTraceUnit {
            pc,
            scratch_changes: None,
            state_changes: None,
            spawned_inners: None,
            stack_pop_count: None,
            stack_additions: None,
        }
    }
}

impl crate::JsonSerializable for SimulationOpcodeTraceUnit {}

impl crate::MsgpackDecodable for SimulationOpcodeTraceUnit {}

