/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "ffi_wasm", tsify(into_wasm_abi, from_wasm_abi))]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct SimulateTransaction200Response {
    /// The version of this response object.
    #[serde(rename = "version")]
    
    
    
    pub version: i32,
    /// The round immediately preceding this simulation. State changes through this round were used to run this simulation.
    #[serde(rename = "last-round")]
    
    
    
    pub last_round: i32,
    /// A result object for each transaction group that was simulated.
    #[serde(rename = "txn-groups")]
    
    
    
    pub txn_groups: Vec<models::SimulateTransactionGroupResult>,
    #[serde(rename = "eval-overrides", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub eval_overrides: Option<models::SimulationEvalOverrides>,
    #[serde(rename = "exec-trace-config", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub exec_trace_config: Option<models::SimulateTraceConfig>,
    #[serde(rename = "initial-states", skip_serializing_if = "Option::is_none")]
    
    #[cfg_attr(feature = "ffi_wasm", tsify(optional))]
    #[cfg_attr(feature = "ffi_uniffi", uniffi(default = None))]
    pub initial_states: Option<models::SimulateInitialStates>,
}

impl SimulateTransaction200Response {
    #[cfg_attr(feature = "ffi_uniffi", uniffi::constructor)]
    #[cfg_attr(feature = "ffi_wasm", wasm_bindgen(constructor))]
    pub fn new(
        version: i32,last_round: i32,txn_groups: Vec<models::SimulateTransactionGroupResult>, eval_overrides: Option<models::SimulationEvalOverrides>, exec_trace_config: Option<models::SimulateTraceConfig>, initial_states: Option<models::SimulateInitialStates>
    ) -> SimulateTransaction200Response {
        SimulateTransaction200Response {
            version: version,
            last_round: last_round,
            txn_groups: txn_groups,
            eval_overrides: eval_overrides,
            exec_trace_config: exec_trace_config,
            initial_states: initial_states,
        }
    }
}

impl crate::JsonSerializable for SimulateTransaction200Response {}

impl crate::MsgpackDecodable for SimulateTransaction200Response {}

