/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "ffi_wasm", tsify(into_wasm_abi, from_wasm_abi))]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct TealDisassemble200Response {
    /// disassembled Teal code
    #[serde(rename = "result")]
    
    
    
    pub result: String,
}

impl TealDisassemble200Response {
    pub fn new(result: String) -> TealDisassemble200Response {
        TealDisassemble200Response {
            result,
        }
    }
}

impl crate::JsonSerializable for TealDisassemble200Response {}


