[package]
name = "algokit_algo25_ffi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[features]
default = ["ffi_uniffi"]
ffi_uniffi = ["dep:uniffi"]

[dependencies]
algokit_algo25 = { path = "../algokit_algo25" }
uniffi = { workspace = true, features = [
  "scaffolding-ffi-buffer-fns",
], optional = true }

[build-dependencies]
uniffi = { workspace = true, features = [
  "build",
  "scaffolding-ffi-buffer-fns",
] }
