[build-system]
requires = ["maturin>=1.5,<2"]
build-backend = "maturin"

[project]
name = "algokit_transact"
version = "0.1.0"
requires-python = ">=3.8,<4.0"
dependencies = ["pynacl>=1.5.0,<2.0.0", "cffi>=1.17.1"]

[tool.maturin]
manifest-path = "../../../crates/algokit_transact_ffi/Cargo.toml"
module-name = "_algokit_transact"

include = ["algokit_transact/py.typed", "algokit_transact/__init__.py"]

[tool.pytest.ini_options]
markers = ["group_generic_transaction_tests", "group_transaction_tests"]

[tool.poetry.group.dev.dependencies]
maturin = [
    { version = ">=1.8.2", markers = "platform_system != 'Linux'" },
    { version = ">=1.8.2", extras = [
        "patchelf",
    ], markers = "platform_system == 'Linux'" },
]
pynacl = ">=1.5.0"
pytest = ">=7.4.4"
