# coding: utf-8

"""
    Algod REST API.

    API endpoint for algod operations.

    The version of the OpenAPI document: 0.0.1
    Contact: contact@algorand.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import pytest
import json
from pydantic import ValidationError

from algorand_algod_client.models.raw_transaction200_response import RawTransaction200Response

@pytest.fixture
def _data_minimal():
    """Fixture providing minimal data for RawTransaction200Response."""
    return {
        "txId": ''
    }

@pytest.fixture
def _data_full():
    """Fixture providing complete data for RawTransaction200Response."""
    return {
        "txId": ''
    }

class TestRawTransaction200Response:
    """RawTransaction200Response test cases"""

    def test_RawTransaction200Response_create_minimal(self, _data_minimal):
        """Test RawTransaction200Response creation with minimal data."""
        instance = RawTransaction200Response(**_data_minimal)
        assert hasattr(instance, "tx_id")
        
    def test_RawTransaction200Response_create_full(self, _data_full):
        """Test RawTransaction200Response creation with all fields."""
        instance = RawTransaction200Response(**_data_full)
        assert hasattr(instance, "tx_id")
        
    def test_RawTransaction200Response_to_dict(self, _data_full):
        """Test RawTransaction200Response serialization to dict."""
        instance = RawTransaction200Response(**_data_full)
        result = instance.to_dict()
        # Check that to_dict returns a dictionary
        assert isinstance(result, dict)
        # Check all fields are present in the serialized result
        # Only check defined values - None values might be excluded
        if _data_full.get("txId") is not None:
            assert "txId" in result
        
    def test_RawTransaction200Response_to_str(self, _data_full):
        """Test RawTransaction200Response string representation is JSON-compatible."""
        instance = RawTransaction200Response(**_data_full)
        string_repr = instance.to_json()
        # Verify the string representation can be parsed as JSON
        try:
            json.loads(string_repr)
            json_valid = True
        except:
            json_valid = False
        assert json_valid, "String representation should be valid JSON"
