# We'll set templateDir via command line, don't specify it here
additionalProperties:
  packageName: "algod_client"
  packageVersion: "1.0.0"
  disallowAdditionalPropertiesIfNotPresent: false
  useOneOfDiscriminatorLookup: true
  useUv: true  # Set to true to use uv, or false to use poetry
  usePoetryCli: false  # Set to true to use poetry instead of uv
  
# Define import mappings for all models
importMappings:
  Account: "algo_models.account.Account"
  Address: "algo_models.address.Address"
  Transaction: "algo_models.transaction.Transaction"
  # Add all the models your API needs here
  
# Use this to specify extra files
files:
  README.md: {}  # This will copy README.md template as is 
