name: API Clients CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/api_clients_ci.yml'
  workflow_dispatch:

env:
  CRATE: algokit_transact

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup api tools
        working-directory: api
        run: bun install

      - name: Generate TypeScript client
        working-directory: api
        run: bun run scripts/generate-algod-clients.ts --target typescript
      
      - name: Upload TypeScript client
        uses: actions/upload-artifact@v4
        with:
          name: algokit-algod-api-ts
          path: api/api_clients/typescript
          retention-days: 1

      - name: Generate Python client
        working-directory: api
        run: bun run scripts/generate-algod-clients.ts --target python
      
      - name: Upload Python client
        uses: actions/upload-artifact@v4
        with:
          name: algokit-algod-api-py
          path: api/api_clients/python
          retention-days: 1

  algokit-algod-api-ts:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85.0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Download TypeScript client
        uses: actions/download-artifact@v4
        with:
          name: algokit-algod-api-ts
          path: api/api_clients/typescript

      - name: Install AlgoKit
        run: pipx install algokit
          
      - name: Start localnet
        run: algokit localnet start

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'api/api_clients/typescript/package.json'

      - name: Build TypeScript ffi package
        run: bun scripts/build ${{ env.CRATE }} typescript

      - name: Test TypeScript client
        working-directory: api/api_clients/typescript
        run: |
          npm install
          npm run test

  algokit-algod-api-py:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85.0
      
      - name: Download Python client
        uses: actions/download-artifact@v4
        with:
          name: algokit-algod-api-py
          path: api/api_clients/python
          
      - name: Install AlgoKit
        run: pipx install algokit
          
      - name: Start localnet
        run: algokit localnet start

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Test Python client
        working-directory: api/api_clients/python
        run: |
          poetry install
          poetry run pytest 
