name: Polytest Validate

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CRATE: algokit_transact

jobs:
  validate:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85.0
      - name: Polytest Validate
        run: cd crates/${{ env.CRATE }}_ffi && cargo bin polytest validate
