name: TypeScript CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

env:
  CRATE: algo_models

jobs:
  build_and_test:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85.0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Build
        run: bun scripts/build ${{ env.CRATE }} typescript
      - name: Test
        run: cd packages/typescript/${{ env.CRATE }} && bun test
